services:
  - type: web
    name: telemedicine
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn telemedicine.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4